# docker-compose.yml
version: '3.8'

services:
  etl-pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./test:/app/test
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: ["--all", "--warehouse"]
    depends_on:
      - mongodb
    networks:
      - etl-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db
    networks:
      - etl-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - etl-network

networks:
  etl-network:
    driver: bridge

volumes:
  mongodb_data: